name: Lint, Build, & Test Code Base

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_build_test:
    name: Lint, Build, & Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

      - name: Lint
        run: yarn lint
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

      - name: Build
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

      - name: Test
        run: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
